apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: openldap-operator-manager-role
rules:
- apiGroups:
  - openldap.kwonjin.click
  resources:
  - openldapclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.kwonjin.click
  resources:
  - openldapclusters/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.kwonjin.click
  resources:
  - openldapclusters/status
  verbs:
  - get
  - patch
  - update
