# permissions for end users to edit openldapclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openldapcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openldap-operator
    app.kubernetes.io/part-of: openldap-operator
    app.kubernetes.io/managed-by: kustomize
  name: openldapcluster-editor-role
rules:
- apiGroups:
  - openldap.kwonjin.click
  resources:
  - openldapclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.kwonjin.click
  resources:
  - openldapclusters/status
  verbs:
  - get
