apiVersion: openldap.kwonjin.click/v1
kind: OpenldapCluster
metadata:
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: openldap
    app.kubernetes.io/part-of: openldap-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openldap-operator
  name: openldap
  namespace: tools
spec:
  image: qwp1216/openldap:2.6.4-repl
  imagePullPolicy: Always
  replicas: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  storage:
    volumeClaimTemplate:
      storageClassName: standard
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  openldapConfig:
    tls:
      enabled: false
    adminUsername: admin
    adminPassword:
      key: password
      name: openldap
    configUsername: config
    configPassword:
      key: password
      name: openldap
    root: dc=cluster,dc=local
    seedData:
      configMap:
        name: openldap-bootstrap
    env:
      - name: BITNAMI_DEBUG
        value: "true"
  monitor:
    enabled: false
  ports:
    ldap: 1389
