apiVersion: openldap.kwonjin.click/v1
kind: OpenldapCluster
metadata:
  labels:
    app.kubernetes.io/name: openldap
    app.kubernetes.io/instance: openldap
    app.kubernetes.io/part-of: openldap-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openldap-operator
  name: openldap
  namespace: tools
spec:
  replicas: 3
  template:
    image: qwp1216/openldap:2.6.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: BITNAMI_DEBUG
        value: "true"
    ports:
      ldap: 1389
  storage:
    volumeClaimTemplate:
      storageClassName: standard
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  openldapConfig:
    tls:
      enabled: false
    adminUsername: admin
    adminPassword:
      key: password
      name: openldap
    root: dc=cluster,dc=local
    seedData:
      configMap:
        name: openldap-bootstrap
  monitor:
    enabled: true

