apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap-operator.fullname" . }}
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "openldap-operator.selectorLabels" . | nindent 4 }}
