{{- if .Values.webhook.validating.create }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "openldap-operator.fullname" . }}-admission
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ include "openldap-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-openldap-kwonjin-click-v1-openldapcluster
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
  name: vopenldapcluster.kb.io
  rules:
  - apiGroups:
    - openldap.kwonjin.click
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openldapclusters
  sideEffects: None
{{- end }}