{{- if or .Values.webhook.mutating.create .Values.webhook.validating.create }}
{{- $altList := list (printf "%s.%s.svc" (include "openldap-operator.fullname" .) .Release.Namespace) (printf "%s-admission.%s" (include "openldap-operator.fullname" .) .Release.Namespace) (include "openldap-operator.fullname" .) }}
{{- $ca := genCA (printf "%s-admission.%s.svc" (include "openldap-operator.fullname" .) .Release.Namespace) 365 }}
{{- $cert := genSignedCert (include "openldap-operator.fullname" .) nil $altList 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap-operator.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
type: Opaque
data:
  tls.key: {{ $cert.Key | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
{{- if .Values.webhook.mutating.create }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "openldap-operator.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ include "openldap-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-openldap-kwonjin-click-v1-openldapcluster
      port: {{ .Values.service.port }}
    caBundle: {{ $ca.Cert | b64enc | quote }}
  failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
  name: vopenldapcluster.kb.io
  rules:
    - apiGroups:
        - openldap.kwonjin.click
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - openldapclusters
  sideEffects: None
{{- end }}
{{- if .Values.webhook.validating.create }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "openldap-operator.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ include "openldap-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-openldap-kwonjin-click-v1-openldapcluster
      port: {{ .Values.service.port }}
    caBundle: {{ $ca.Cert | b64enc | quote }}
  failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
  name: vopenldapcluster.kb.io
  rules:
    - apiGroups:
        - openldap.kwonjin.click
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - openldapclusters
  sideEffects: None
{{- end }}
{{- end }}