name: Helm Chart Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      BUILDER: "multi-arch"
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u qwp1216 -p ${DOCKER_PWD}

      - name: Build Application
        run: |
          make docker-buildx \
            IMG=${DOCKER_REGISTRY}:$(helm show chart charts/openldap-operator | grep version | awk -F": " '{print $2}' | xargs echo -n) \
            PLATFORMS=linux/amd64,linux/arm64

  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkou
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
